/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'glauber' at '13/09/16 21:27' with Gradle 2.12
 *
 * @author glauber, @date 13/09/16 21:27
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
